var messages = [
    {type: 'affirmation', msg: "If you are irritated by every rub, how will your mirror be polished?", id: 0, fav: false},
    {type: 'affirmation', msg: "I believe I can be all that I want to be.", id: 1, fav: false},
    {type: 'affirmation', msg: "I am in the process of becoming the best version of myself.", id: 2, fav: false},
    {type: 'affirmation', msg: "I have the freedom & power to create the life I desire.", id: 3, fav: false},
    {type: 'affirmation', msg: "I choose to be kind to myself and love myself unconditionally.", id: 4, fav: false},
    {type: 'affirmation', msg: "My possibilities are endless.", id: 5, fav: false},
    {type: 'affirmation', msg: "I am worthy of my dreams.", id: 6, fav: false},
    {type: 'affirmation', msg: "I am enough.", id: 7, fav: false},
    {type: 'affirmation', msg: "I deserve to be healthy and feel good.", id: 8, fav: false},
    {type: 'affirmation', msg: "The cure for the pain is the pain", id: 9, fav: false},
    {type: 'affirmation', msg: "I honor my body by trusting the signals that it sends me.", id: 10, fav: false},
    {type: 'affirmation', msg: "I manifest perfect health by making smart choices.", id: 11, fav: false},
    {type: 'mantra', msg: "Don't let yesterday take up too much of today.", id: 12, fav: false},
    {type: 'mantra',msg: "Every day is a second chance.", id: 13, fav: false},
    {type: 'mantra',msg: "Tell the truth and love everyone.", id: 14, fav: false},
    {type: 'mantra',msg: "I will have a good day, because it is my choice.", id: 15, fav: false},
    {type: 'mantra',msg: "I am free from sadness.", id: 16, fav: false},
    {type: 'mantra',msg: "In the beginning it is you, in the middle it is you and in the end it is you.", id: 17, fav: false},
    {type: 'mantra',msg: "I am present now.", id: 18, fav: false},
    {type: 'mantra',msg: "Inhale the future, exhale the past.", id: 19, fav: false},
    {type: 'mantra',msg: "You are not a drop in the ocean. You are the entire ocean in a drop.", id: 20, fav: false},
    {type: 'mantra',msg: "Stop acting so small. You are the universe in ecstatic motion.", id: 21, fav: false}
];